### ISSUE TITLE
Installation tips?

### ISSUE THREAD

**Issue by jamenlang** [bobthebutcher/cupi#1]
Python version?

Installation tips?

I see that it requires unittest so i installed that with pip3

I don't know where cupi.cake is coming from.

from cupi.cake import CUPI
ImportError: No module named 'cupi.cake'; 'cupi' is not a package

**Comment by bwks** [comment]
I have updated the doco, please have a look at that and let me know how you go. If I get time I can add a setup package for this, but I am not using it in my current role so its not very high on my priority list.

**Comment by cybergakusei** [comment]
Hello, I'm new to python so forgive me ahead of time if this is a dumb question but, I can't seem to clone the repo for cake. 
At first, I got a ModuleNotFoundError: no module named 'cupi'.
Now I get the following: 
 python -m pip install -vvv --index-url https://github.com/bobthebutcher/cupi.git/ cupi
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
Created temporary directory: C:\Users\anon\AppData\Local\Temp\pip-ephem-wheel-cache-a6v00mz4
Created temporary directory: C:\Users\anon\AppData\Local\Temp\pip-req-tracker-w5bbb5p6
Created requirements tracker 'C:\\Users\\anon\\AppData\\Local\\Temp\\pip-req-tracker-w5bbb5p6'
Created temporary directory: C:\Users\anon\AppData\Local\Temp\pip-install-w5i4mvkx
Looking in indexes: https://github.com/bobthebutcher/cupi.git/
Collecting cupi
  1 location(s) to search for versions of cupi:
  * https://github.com/bobthebutcher/cupi.git/cupi/
  Getting page https://github.com/bobthebutcher/cupi.git/cupi/
  Looking up "https://github.com/bobthebutcher/cupi.git/cupi/" in the cache
  No cache entry available
  Starting new HTTPS connection (1): github.com:443
  https://github.com:443 "GET /bobthebutcher/cupi.git/cupi/ HTTP/1.1" 404 None
  Status code 404 not in (200, 203, 300, 301)
  Could not fetch URL https://github.com/bobthebutcher/cupi.git/cupi/: 404 Client Error: Not Found for url: https://github.com/bobthebutcher/cupi.git/cupi/ - skipping
  Could not find a version that satisfies the requirement cupi (from versions: )
Cleaning up...
Removed build tracker 'C:\\Users\\anon\\AppData\\Local\\Temp\\pip-req-tracker-w5bbb5p6'
No matching distribution found for cupi
Exception information:
Traceback (most recent call last):
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\basecommand.py", line 141, in main
    status = self.run(options, args)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\commands\install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\operations\prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\req\req_install.py", line 308, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\anon\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\_internal\index.py", line 543, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for cupi
Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
1 location(s) to search for versions of pip:
* https://github.com/bobthebutcher/cupi.git/pip/
Getting page https://github.com/bobthebutcher/cupi.git/pip/
Looking up "https://github.com/bobthebutcher/cupi.git/pip/" in the cache
No cache entry available
Starting new HTTPS connection (1): github.com:443
https://github.com:443 "GET /bobthebutcher/cupi.git/pip/ HTTP/1.1" 404 None
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://github.com/bobthebutcher/cupi.git/pip/: 404 Client Error: Not Found for url: https://github.com/bobthebutcher/cupi.git/pip/ - skipping

Do I need to run a particular version of Python or pip?

**Comment by bwks** [comment]
@cybergakusei I have not packaged this up so I dont think you will be able to install it the way you are attempting to do it. Check the readme for usage instructions.

**Comment by cybergakusei** [comment]
Thanks for your response, I got it now. Apparently I'm a noob with Git too. Thank you!

**Comment by bwks** [comment]
Great to hear
